### ISSUE TITLE
我设计了一种新型的排序算法，是一个改进型的桶排序，平均速度是快排的 3 倍，最快达到 20 倍，可以试试

### ISSUE THREAD

**Issue by hackware1993** [zhangyunhao116/pdqsort#3]
https://github.com/hackware1993/ChenSort

**Comment by hackware1993** [comment]
Chen sort 是一个混合排序，如果将底层替换为 pdqsort，那它的速度也能达到 pdqsort 的三倍

**Comment by zhangyunhao116** [comment]
The Go version of pdqsort has been merged into Go runtime, we don't discuss algorithm differences in this repository, if you have a better sorting algorithm, maybe hacknews is a better place, Thanks!
