### ISSUE TITLE
Export the Ordered interface

### ISSUE THREAD

**Issue by ivanjaros** [zhangyunhao116/pdqsort#5]
I want to use your sorting in my functions(like Unique) but since `ordered` is not exported I cannot use it as constraint.

**Comment by zhangyunhao116** [comment]
Hi, this package has merged into the Go runtime from 1.19, if you want to use the generics version of pdqsort, you can try https://github.com/golang/exp/blob/master/slices/sort.go#L18
(The ordered type is still in an experimental state, so the only way we can use it is by using the `exp` packages)

**Comment by ivanjaros** [comment]
i copied it for now.
