### ISSUE TITLE
 go那个版本并入了我在1.92 没看到呀

### ISSUE THREAD

**Issue by hbmask** [zhangyunhao116/pdqsort#6]
go那个版本并入了我在1.92 没看到呀
在1.92 基础库里面 已经有了?

**Comment by zhangyunhao116** [comment]
Related commit: https://github.com/golang/go/commit/72e77a7f41bbf45d466119444307fd3ae996e257

**Comment by hbmask** [comment]
您的来信我已经收到，我会尽快回复你。
