### ISSUE TITLE
How to replace?

### ISSUE THREAD

**Issue by ivanjaros** [zhangyunhao116/pdqsort#7]
Hi, so obviously this was merged into Go std library. But how do I replace `pdqsort.Slice` now? Go requires _less_ function as argument and I don't see any new functions added to std. So how do i achieve the same functionality?

**Comment by zhangyunhao116** [comment]
Hi, it seems like you need to update your Go version to 1.21. In this latest release, the slices package has been merged into the standard library. You can use the `slices.Sort`(https://pkg.go.dev/slices@master#Sort) to replace the `pdqsort.Slice`.

https://tip.golang.org/doc/go1.21#slices
